name 'httpd'
maintainer 'IBM Corp'
maintainer_email ''
license 'Copyright IBM Corp. 2016, 2017'
depends 'ibm_cloud_utils'
description <<-EOH
## DESCRIPTION
The Apache HTTP cookbook provides the necessary resources to install and manage Apache HTTP Server
## Platforms Support
* RHEL 6.x
* RHEL 7.x

## Versions
Apache HTTP Server 2.4

## Use Cases
* Single installation with no configuration.
* Single installation with SSL and Proxy configuration

## Platform Pre-Requisites
* Linux YUM Repository - An onsite linux YUM Repsoitory is required.

EOH

version '1.1.24'

attribute 'httpd/archive_names/apr/binary',
          :default => 'apr-1.5.2-1.x86_64.rpm',
          :description => 'HTTP Server apr binary',
          :displayname => 'HTTP Server apr binary',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/archive_names/apr-devel/binary',
          :default => 'apr-devel-1.5.2-1.x86_64.rpm',
          :description => 'HTTP Server apr-devel binary',
          :displayname => 'HTTP Server apr-devel binary',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/archive_names/apr-util/binary',
          :default => 'apr-util-1.5.4-1.x86_64.rpm',
          :description => 'HTTP Server apr util binary',
          :displayname => 'HTTP Server apr util binary',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/archive_names/httpd/binary',
          :default => 'httpd-2.4.25-1.x86_64.rpm',
          :description => 'HTTP Server binary',
          :displayname => 'HTTP Server binary',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/archive_names/httpd-tools/binary',
          :default => 'httpd-tools-2.4.25-1.x86_64.rpm',
          :description => 'HTTP Server httpd-tools binary',
          :displayname => 'HTTP Server httpd-tools binary',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/archive_names/mod.proxy/binary',
          :default => 'mod_proxy_html-2.4.25-1.x86_64.rpm',
          :description => 'HTTP Server mod_proxy binary',
          :displayname => 'HTTP Server mod_proxy binary',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/archive_names/mod_ssl/binary',
          :default => 'mod_ssl-2.4.25-1.x86_64.rpm',
          :description => 'HTTP Server mod_ssl binary',
          :displayname => 'HTTP Server mod_ssl binary',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/conf_file_mode',
          :default => '0640',
          :description => 'httpd conf_file_mode',
          :displayname => 'httpd conf_file_mode',
          :parm_type => 'none',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/custom_log',
          :default => 'access_log',
          :description => 'httpd custom_log',
          :displayname => 'httpd custom_log',
          :parm_type => 'none',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/custom_log_format',
          :default => 'combined',
          :description => 'httpd custom_log_format',
          :displayname => 'httpd custom_log_format',
          :parm_type => 'none',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/data_dir_mode',
          :default => '0750',
          :description => 'httpd data_dir_mode',
          :displayname => 'httpd data_dir_mode',
          :parm_type => 'none',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/directory_index',
          :default => 'index.html info.php',
          :description => 'httpd directory_index',
          :displayname => 'httpd directory_index',
          :parm_type => 'none',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/document_root',
          :default => '',
          :description => 'httpd document_root',
          :displayname => 'httpd document_root',
          :parm_type => 'none',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/enable_MMAP',
          :default => 'off',
          :description => 'httpd enable_MMAP',
          :displayname => 'httpd enable_MMAP',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/enable_send_file',
          :default => 'off',
          :description => 'httpd enable_send_file',
          :displayname => 'httpd enable_send_file',
          :parm_type => 'none',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/error_log',
          :default => 'error_log',
          :description => 'httpd error_log',
          :displayname => 'httpd error_log',
          :parm_type => 'none',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/hostname_lookups',
          :default => 'off',
          :description => 'httpd hostname_lookups',
          :displayname => 'httpd hostname_lookups',
          :parm_type => 'none',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/httpd_home',
          :default => '',
          :description => 'httpd httpd_home',
          :displayname => 'httpd httpd_home',
          :parm_type => 'none',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/install_dir',
          :default => '',
          :description => 'httpd install_dir',
          :displayname => 'httpd install_dir',
          :parm_type => 'none',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/install_from_repo',
          :default => 'true',
          :description => 'httpd install_from_repo',
          :displayname => 'httpd install_from_repo',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/keep_alive',
          :default => 'off',
          :description => 'httpd keep_alive',
          :displayname => 'httpd keep_alive',
          :parm_type => 'none',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/keep_alive_timeout',
          :default => '15',
          :description => 'httpd keep_alive_timeout',
          :displayname => 'httpd keep_alive_timeout',
          :parm_type => 'none',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/listen',
          :default => '80',
          :description => 'httpd listen',
          :displayname => 'httpd listen',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/log_dir',
          :default => '',
          :description => 'httpd log_dir',
          :displayname => 'httpd log_dir',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/log_level',
          :default => 'warn',
          :description => 'httpd log_level',
          :displayname => 'httpd log_level',
          :parm_type => 'none',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/max_keep_alive_requests',
          :default => '100',
          :description => 'httpd max_keep_alive_requests',
          :displayname => 'httpd max_keep_alive_requests',
          :parm_type => 'none',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/os_users/daemon/comment',
          :default => 'httpd daemon user',
          :description => 'httpd os_users daemon comment',
          :displayname => 'httpd os_users daemon comment',
          :parm_type => 'none',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/os_users/daemon/gid',
          :default => 'apache',
          :description => 'httpd os_users daemon gid',
          :displayname => 'httpd os_users daemon gid',
          :parm_type => 'none',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/os_users/daemon/home',
          :default => '',
          :description => 'httpd os_users daemon home',
          :displayname => 'httpd os_users daemon home',
          :parm_type => 'none',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/os_users/daemon/ldap_user',
          :default => 'false',
          :description => 'httpd os_users daemon ldap_user',
          :displayname => 'httpd os_users daemon ldap_user',
          :parm_type => 'none',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/os_users/daemon/name',
          :default => 'apache',
          :description => 'httpd os_users daemon name',
          :displayname => 'httpd os_users daemon name',
          :parm_type => 'none',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/os_users/daemon/shell',
          :default => '/sbin/nologin',
          :description => 'httpd os_users daemon shell',
          :displayname => 'httpd os_users daemon shell',
          :parm_type => 'none',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/os_users/web_content_owner/comment',
          :default => 'httpd daemon user',
          :description => 'httpd os_users web_content_owner comment',
          :displayname => 'httpd os_users web_content_owner comment',
          :parm_type => 'none',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/os_users/web_content_owner/gid',
          :default => 'apache',
          :description => 'httpd os_users web_content_owner gid',
          :displayname => 'httpd os_users web_content_owner gid',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/os_users/web_content_owner/home',
          :default => '/home/webmaster',
          :description => 'httpd os_users web_content_owner home',
          :displayname => 'httpd os_users web_content_owner home',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/os_users/web_content_owner/ldap_user',
          :default => 'false',
          :description => 'httpd os_users web_content_owner ldap_user',
          :displayname => 'httpd os_users web_content_owner ldap_user',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/os_users/web_content_owner/name',
          :default => 'webmaster',
          :description => 'httpd os_users web_content_owner name',
          :displayname => 'httpd os_users web_content_owner name',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/os_users/web_content_owner/shell',
          :default => '/bin/bash',
          :description => 'httpd os_users web_content_owner shell',
          :displayname => 'httpd os_users web_content_owner shell',
          :parm_type => 'none',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/php_mod_enabled',
          :default => 'true',
          :description => 'httpd php_mod_enabled',
          :displayname => 'httpd php_mod_enabled',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/prefork_max_clients',
          :default => '256',
          :description => 'httpd prefork_max_clients',
          :displayname => 'httpd prefork_max_clients',
          :parm_type => 'none',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/prefork_max_requests_per_child',
          :default => '4000',
          :description => 'httpd prefork_max_requests_per_child',
          :displayname => 'httpd prefork_max_requests_per_child',
          :parm_type => 'none',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/prefork_max_spare_servers',
          :default => '20',
          :description => 'httpd prefork_max_spare_servers',
          :displayname => 'httpd prefork_max_spare_servers',
          :parm_type => 'none',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/prefork_min_spare_servers',
          :default => '5',
          :description => 'httpd prefork_min_spare_servers',
          :displayname => 'httpd prefork_min_spare_servers',
          :parm_type => 'none',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/prefork_server_limit',
          :default => '256',
          :description => 'httpd prefork_server_limit',
          :displayname => 'httpd prefork_server_limit',
          :parm_type => 'none',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/prefork_start_servers',
          :default => '8',
          :description => 'httpd prefork_start_servers',
          :displayname => 'httpd prefork_start_servers',
          :parm_type => 'none',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/prereq_packages',
          :default => '',
          :description => 'httpd prereq_packages',
          :displayname => 'httpd prereq_packages',
          :parm_type => 'none',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'array'
attribute 'httpd/proxy',
          :default => 'true',
          :description => 'Global proxy settings configuration',
          :displayname => 'Global proxy settings',
          :parm_type => 'none',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/server_admin',
          :default => 'webmaster@localhost',
          :description => 'httpd server_admin',
          :displayname => 'httpd server_admin',
          :parm_type => 'none',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/server_name',
          :default => '',
          :description => 'httpd server_name',
          :displayname => 'httpd server_name',
          :parm_type => 'none',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/server_root',
          :default => '',
          :description => 'httpd server_root',
          :displayname => 'httpd server_root',
          :parm_type => 'none',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/service_name',
          :default => 'httpd',
          :description => 'httpd service_name',
          :displayname => 'httpd service_name',
          :parm_type => 'none',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/ssl/install_mod_ssl',
          :default => 'true',
          :description => 'Installs mod SSL or not',
          :displayname => 'InstallModSSL',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/ssl/sslcompression',
          :default => '',
          :description => 'Enable SSL compression',
          :displayname => 'EnableSSLCompression',
          :parm_type => 'none',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/ssl/sslproxycacertificatefile',
          :default => '',
          :description => 'SSL proxy Certificate file name',
          :displayname => 'SSLProxyCertFileName',
          :parm_type => 'none',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/ssl/sslproxycacertificatepath',
          :default => '',
          :description => 'SSL proxy Certificate file path',
          :displayname => 'SSLProxyCertFilePath',
          :parm_type => 'none',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/ssl/sslproxycarevocationcheck',
          :default => '',
          :description => 'SSL proxy CA revocation check',
          :displayname => 'SSLProxyCARevocationCheck',
          :parm_type => 'none',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/ssl/sslproxycarevocationfile',
          :default => '',
          :description => 'SSL proxy CA revocation file',
          :displayname => 'SSLProxyCARevocationFile',
          :parm_type => 'none',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/tarball',
          :description => 'RHEL tarball file',
          :displayname => 'RHEL tarball file'
attribute 'httpd/timeout',
          :default => '60',
          :description => 'httpd timeout',
          :displayname => 'httpd timeout',
          :parm_type => 'none',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/use_canonical_name',
          :default => 'off',
          :description => 'httpd use_canonical_name',
          :displayname => 'httpd use_canonical_name',
          :parm_type => 'none',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/version',
          :default => '',
          :description => 'httpd version',
          :displayname => 'httpd version',
          :parm_type => 'none',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/vhosts_enabled',
          :default => 'true',
          :description => 'Vhost enabled',
          :displayname => 'VhostEnabled',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/virtualhosts/default_http_server/custom_log',
          :default => '',
          :description => 'Vhost custom log dir',
          :displayname => 'DefaultHTTPVhostCustomLogDir',
          :parm_type => 'none',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/virtualhosts/default_http_server/custom_log_format',
          :default => 'combined',
          :description => 'Vhost custom log format',
          :displayname => 'DefaultHTTPVhostCustomLogFormat',
          :parm_type => 'none',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/virtualhosts/default_http_server/document_root',
          :default => '',
          :description => 'Vhost document root',
          :displayname => 'DefaultHTTPVhostDocumentRoot',
          :parm_type => 'none',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/virtualhosts/default_http_server/error_log',
          :default => '',
          :description => 'Vhost error log dir',
          :displayname => 'DefaultHTTPVhostErrorLogDir',
          :parm_type => 'none',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/virtualhosts/default_http_server/global_ssl_config',
          :default => 'true',
          :description => 'Global SSL configuration',
          :displayname => 'DefaultHTTPGlobalSSLConfig',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/virtualhosts/default_http_server/log_dir',
          :default => '',
          :description => 'Vhost log dir',
          :displayname => 'DefaultHTTPVhostLogDir',
          :parm_type => 'none',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/virtualhosts/default_http_server/server_admin',
          :default => '',
          :description => 'Vhost Server admin',
          :displayname => 'DefaultHTTPVhostServerAdmin',
          :parm_type => 'none',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/virtualhosts/default_http_server/server_name',
          :default => '',
          :description => 'Vhost server name for directing requests',
          :displayname => 'DefaultHTTPVhostServerName',
          :parm_type => 'none',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/virtualhosts/default_http_server/ssl_enabled',
          :default => 'false',
          :description => 'SSL Enabled for Virtual Host',
          :displayname => 'DefaultHTTPVhostSSLEnabled',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/virtualhosts/default_http_server/vhost_listen',
          :default => '80',
          :description => 'Port Vhost listens on',
          :displayname => 'DefaultHTTPVhostPort',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/virtualhosts/default_http_server/vhost_type',
          :default => 'name_based',
          :description => 'name_based or ip_based',
          :displayname => 'DefaultHTTPVhostType',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/virtualhosts/default_https_server/custom_log',
          :default => '',
          :description => 'Vhost custom log dir',
          :displayname => 'DefaultHTTPSVhostCustomLogDir',
          :parm_type => 'none',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/virtualhosts/default_https_server/custom_log_format',
          :default => 'combined',
          :description => 'Vhost custom log format',
          :displayname => 'DefaultHTTPSVhostCustomLogFormat',
          :parm_type => 'none',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/virtualhosts/default_https_server/document_root',
          :default => '',
          :description => 'Vhost document root',
          :displayname => 'DefaultHTTPSVhostDocumentRoot',
          :parm_type => 'none',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/virtualhosts/default_https_server/error_log',
          :default => '',
          :description => 'Vhost error log dir',
          :displayname => 'DefaultHTTPSVhostErrorLogDir',
          :parm_type => 'none',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/virtualhosts/default_https_server/global_ssl_config',
          :default => 'true',
          :description => 'Global SSL configuration',
          :displayname => 'DefaultHTTPSGlobalSSLConfig',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/virtualhosts/default_https_server/log_dir',
          :default => '',
          :description => 'Vhost log dir',
          :displayname => 'DefaultHTTPSVhostLogDir',
          :parm_type => 'none',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/virtualhosts/default_https_server/server_admin',
          :default => '',
          :description => 'Vhost Server admin',
          :displayname => 'DefaultHTTPSVhostServerAdmin',
          :parm_type => 'none',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/virtualhosts/default_https_server/server_name',
          :default => '',
          :description => 'Vhost server name for directing requests',
          :displayname => 'DefaultHTTPSVhostServerName',
          :parm_type => 'none',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/virtualhosts/default_https_server/ssl_enabled',
          :default => 'true',
          :description => 'SSL Enabled for Virtual Host',
          :displayname => 'DefaultHTTPSSSLEnabled',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/virtualhosts/default_https_server/vhost_listen',
          :default => '443',
          :description => 'Port Vhost listens on',
          :displayname => 'DefaultHTTPSVhostPort',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/virtualhosts/default_https_server/vhost_type',
          :default => 'name_based',
          :description => 'name_based or ip_based',
          :displayname => 'DefaultHTTPSVhostType',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/worker_max_clients',
          :default => '25',
          :description => 'httpd worker_max_clients',
          :displayname => 'httpd worker_max_clients',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/worker_max_requests_per_child',
          :default => '0',
          :description => 'httpd worker_max_requests_per_child',
          :displayname => 'httpd worker_max_requests_per_child',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/worker_max_spare_servers',
          :default => '25',
          :description => 'httpd worker_max_spare_servers',
          :displayname => 'httpd worker_max_spare_servers',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/worker_min_spare_servers',
          :default => '300',
          :description => 'httpd worker_min_spare_servers',
          :displayname => 'httpd worker_min_spare_servers',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/worker_server_limit',
          :default => '75',
          :description => 'httpd worker_server_limit',
          :displayname => 'httpd worker_server_limit',
          :parm_type => 'node',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
attribute 'httpd/worker_start_servers',
          :default => '4',
          :description => 'httpd worker_start_servers',
          :displayname => 'httpd worker_start_servers',
          :parm_type => 'none',
          :precedence_level => 'node',
          :required => 'recommended',
          :secret => 'false',
          :selectable => 'false',
          :type => 'string'
recipe 'httpd::cleanup.rb', '
Cleanup recipe (cleanup.rb)
Perform post-install cleanup
'
recipe 'httpd::config_httpd_conf.rb', '
Configure httpd server recipe (config_httpd_conf.rb)
Setup the main server configuration file
'
recipe 'httpd::config_ssl.rb', '
SSL configuration recipe (config_proxy.rb)
Install mod_ssl, create SSL configuration file, create certificates
'
recipe 'httpd::config_vhosts.rb', '
vhost configuration recipe (config_vhost.rb)
Create vhost configuration file
'
recipe 'httpd::default.rb', '
Default recipe (default.rb)
The default recipe for the cookbook. It is recommended to not use the default recipe, but explicitly specify a run_list for the deployment node.
'
recipe 'httpd::gather_evidence.rb', '
Gather evidence recipe (gather_evidence.rb)
Gather evidence that installation was successful
'
recipe 'httpd::install.rb', '
Installation recipe (install.rb)
Perform an installation of selected httpd package on the target node.
'
recipe 'httpd::prereq.rb', '
Prerequisites recipe (prereq.rb)
Perform prerequisite tasks.
'
recipe 'httpd::service.rb', '
Service control recipe (service.rb)
Enable and start the httpd service
'
